# Generated by Django 2.0 on 2018-01-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RICCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='daily',
            name='ric_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.RICCode'),
        ),
    ]
