# Generated by Django 2.0 on 2018-01-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.CharField(max_length=20)),
                ('ric_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.RICCode')),
            ],
        ),
    ]
